import assert from 'node:assert/strict';
import { once } from 'node:events';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import type { AddressInfo } from 'node:net';
import BetterSqlite3 from 'better-sqlite3';
import { openDatabase } from '../../src/platform/db/database.js';
import { ContentAddressedArtifactStore } from '../../src/platform/artifacts/artifact-store.js';
import { DiscoveryWorkspaceService } from '../../src/modules/flow/discovery-workspace-service.js';
import { ProductCandidateService } from '../../src/modules/flow/product-candidate-service.js';
import { createOwnerApiServer } from '../../src/api/owner-api.js';

const token='correct-owner-token-with-at-least-32-characters', origin='http://127.0.0.1:5173';
const workspace='11111111-1111-4111-8111-111111111111', other='22222222-2222-4222-8222-222222222222', candidate='33333333-3333-4333-8333-333333333333', candidateB='33333333-3333-4333-8333-333333333334', foreignCandidate='33333333-3333-4333-8333-333333333335', basket1='44444444-4444-4444-8444-444444444441', basket2='44444444-4444-4444-8444-444444444442', basket3='44444444-4444-4444-8444-444444444443', basket4='44444444-4444-4444-8444-444444444444', basket5='44444444-4444-4444-8444-444444444445';
const roots:string[]=[]; test.afterEach(()=>{for(const root of roots.splice(0))fs.rmSync(root,{recursive:true,force:true});});
async function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'tdn-owner-basket-'));roots.push(root);const databasePath=path.join(root,'db.sqlite'),artifactRoot=path.join(root,'artifacts');const {db}=openDatabase({databasePath});const store=new ContentAddressedArtifactStore(artifactRoot);let wi=0;const discoveries=new DiscoveryWorkspaceService({db,artifactStore:store,uuid:()=>[workspace,other][wi++]!});await discoveries.createWorkspace({contractVersion:'1.0.0',workspaceKey:'one',title:'One'});await discoveries.createWorkspace({contractVersion:'1.0.0',workspaceKey:'two',title:'Two'});let ci=0;const candidates=new ProductCandidateService({db,artifactStore:store,uuid:()=>[candidate,candidateB,foreignCandidate][ci++]!});await candidates.createCandidate({contractVersion:'1.0.0',workspaceId:workspace,candidateKey:'calcium',label:'Calcium'});await candidates.reviseCandidate({contractVersion:'1.0.0',candidateId:candidate,expectedVersion:1,label:'Calcium v2'});await candidates.createCandidate({contractVersion:'1.0.0',workspaceId:workspace,candidateKey:'magnesium',label:'Magnesium'});await candidates.createCandidate({contractVersion:'1.0.0',workspaceId:other,candidateKey:'foreign',label:'Foreign'});db.close();return{databasePath,artifactRoot};}
async function serve(state:Awaited<ReturnType<typeof fixture>>,run:(base:string)=>Promise<void>){let i=0;const api=createOwnerApiServer({...state,writeEnabled:true,token,allowedOrigin:origin,actorId:'owner:local',now:()=>new Date(`2027-01-0${i+1}T00:00:00Z`),uuid:()=>[basket1,basket2,basket3,basket4,basket5][i++]!});api.server.listen(0,'127.0.0.1');await once(api.server,'listening');try{await run(`http://127.0.0.1:${(api.server.address() as AddressInfo).port}`);}finally{await api.close();}}
const headers={authorization:`Bearer ${token}`,'content-type':'application/json',origin};
const endpoint=(base:string,id=workspace)=>`${base}/owner-api/workspaces/${id}/candidate-baskets`;
const body=(version=1,candidateVersion=1,extra:Record<string,unknown>={})=>JSON.stringify({contractVersion:'1.0.0',basketKey:'shortlist',version,candidates:[{candidateId:candidate,candidateVersion}],...extra});

test('OWNER freezes sequential exact revisions, retries exactly, and creates no downstream records',async()=>{const state=await fixture();await serve(state,async(base)=>{const created=await fetch(endpoint(base),{method:'POST',headers,body:body()});assert.equal(created.status,201);const receipt=await created.json() as any;assert.deepEqual(receipt,{contractVersion:'1.0.0',basketId:basket1,workspaceId:workspace,basketKey:'shortlist',version:1,frozenAt:'2027-01-02T00:00:00.000Z',candidateCount:1,exactRetry:false});assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:body()})).status,200);assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:body(3,2)})).status,409);assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:body(2,2)})).status,201);assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:body(1,2)})).status,409);});const db=new BetterSqlite3(state.databasePath);assert.deepEqual(db.prepare('SELECT version FROM flow_candidate_baskets ORDER BY version').all(),[{version:1},{version:2}]);assert.equal((db.prepare('SELECT count(*) n FROM governance_candidate_b7_decisions').get() as any).n,0);assert.equal((db.prepare('SELECT count(*) n FROM flow_product_workspaces').get() as any).n,0);db.close();});

test('concurrent identical basket creates serialize to one create and one exact retry',async()=>{const state=await fixture();await serve(state,async(base)=>{const responses=await Promise.all([fetch(endpoint(base),{method:'POST',headers,body:body()}),fetch(endpoint(base),{method:'POST',headers,body:body()})]);assert.deepEqual(responses.map((response)=>response.status).sort(),[200,201]);const receipts=await Promise.all(responses.map((response)=>response.json() as Promise<any>));assert.equal(new Set(receipts.map((receipt)=>receipt.basketId)).size,1);assert.deepEqual(receipts.map((receipt)=>receipt.exactRetry).sort(),[false,true]);});const db=new BetterSqlite3(state.databasePath);assert.equal((db.prepare('SELECT count(*) n FROM flow_candidate_baskets').get() as any).n,1);db.close();});

test('basket route is closed, protected, URL-scoped, and maps malformed/unknown/cross-workspace safely',async()=>{const state=await fixture();await serve(state,async(base)=>{assert.equal((await fetch(endpoint(base),{method:'POST',headers:{...headers,authorization:''},body:body()})).status,401);assert.equal((await fetch(endpoint(base),{method:'POST',headers:{...headers,origin:'http://evil.local'},body:body()})).status,403);assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:body(1,1,{workspaceId:other})})).status,400);assert.equal((await fetch(endpoint(base,'99999999-9999-4999-8999-999999999999'),{method:'POST',headers,body:body()})).status,404);assert.equal((await fetch(endpoint(base,other),{method:'POST',headers,body:body()})).status,409);assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:JSON.stringify({contractVersion:'1.0.0',basketKey:'x',version:1,candidates:[]})})).status,400);});});

test('exact retry recovers only its missing basket artifact and preserves unrelated files',async()=>{const state=await fixture();const unrelated=await new ContentAddressedArtifactStore(state.artifactRoot).put(Buffer.from('unrelated'));await serve(state,async(base)=>{await fetch(endpoint(base),{method:'POST',headers,body:body()});const db=new BetterSqlite3(state.databasePath);const row=db.prepare('SELECT basket_artifact_sha256 digest FROM flow_candidate_baskets').get() as {digest:string};db.close();const target=path.join(state.artifactRoot,'sha256',row.digest.slice(0,2),row.digest);fs.unlinkSync(target);assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:body()})).status,200);assert.ok(fs.existsSync(target));assert.equal(fs.readFileSync(unrelated.absolutePath,'utf8'),'unrelated');assert.deepEqual(fs.readdirSync(path.join(state.artifactRoot,'.owner-api-requests')),[]);});});

test('OWNER basket schema is generated and registered closed',()=>{const schema=JSON.parse(fs.readFileSync('contracts/api/owner-candidate-basket-api.schema.json','utf8'));assert.equal(schema.$defs.request.additionalProperties,false);assert.equal(schema.$defs.selection.additionalProperties,false);assert.equal(schema.$defs.receipt.additionalProperties,false);assert.match(fs.readFileSync('scripts/generate-foundation-contract.mjs','utf8'),/owner-candidate-basket-api/);});

const selections=(...values:Array<[string,number]>)=>values.map(([candidateId,candidateVersion])=>({candidateId,candidateVersion}));
const basketBody=(basketKey:string,version:number,candidates:Array<{candidateId:string,candidateVersion:number}>)=>JSON.stringify({contractVersion:'1.0.0',basketKey,version,candidates});
function basketCounts(databasePath:string){const db=new BetterSqlite3(databasePath);const result={baskets:(db.prepare('SELECT count(*) n FROM flow_candidate_baskets').get() as any).n,members:(db.prepare('SELECT count(*) n FROM flow_candidate_basket_members').get() as any).n,manifests:(db.prepare('SELECT count(*) n FROM artifact_manifests').get() as any).n};db.close();return result;}
function artifactFiles(root:string){const base=path.join(root,'sha256');return fs.existsSync(base)?fs.readdirSync(base).flatMap(prefix=>fs.readdirSync(path.join(base,prefix)).map(file=>`${prefix}/${file}`)).sort():[];}
const genericIntegrity={error:{code:'integrity_error',message:'Stored workspace data failed integrity verification'}};

 test('multi-member reversed input is an exact deterministic retry with zero database changes',async()=>{const state=await fixture();const firstRequest=basketBody('multi',1,selections([candidateB,1],[candidate,2]));await serve(state,async(base)=>{const first=await fetch(endpoint(base),{method:'POST',headers,body:firstRequest});assert.equal(first.status,201);const before=basketCounts(state.databasePath);const db=new BetterSqlite3(state.databasePath);const changesBefore=(db.prepare('SELECT total_changes() n').get() as any).n;db.close();const retry=await fetch(endpoint(base),{method:'POST',headers,body:basketBody('multi',1,selections([candidate,2],[candidateB,1]))});assert.equal(retry.status,200);assert.equal((await retry.json() as any).exactRetry,true);assert.deepEqual(basketCounts(state.databasePath),before);const check=new BetterSqlite3(state.databasePath);assert.equal((check.prepare('SELECT total_changes() n').get() as any).n,changesBefore);assert.deepEqual(check.prepare('SELECT candidate_id candidateId,position FROM flow_candidate_basket_members ORDER BY position').all(),[{candidateId:candidate,position:0},{candidateId:candidateB,position:1}]);check.close();});});

 test('duplicate IDs, missing revisions, and cross-workspace members fail without basket writes',async()=>{const state=await fixture();const before=basketCounts(state.databasePath);await serve(state,async(base)=>{const duplicate=await fetch(endpoint(base),{method:'POST',headers,body:basketBody('bad',1,selections([candidate,1],[candidate,2]))});assert.equal(duplicate.status,400);const missing=await fetch(endpoint(base),{method:'POST',headers,body:basketBody('bad',1,selections([candidate,99]))});assert.equal(missing.status,404);const cross=await fetch(endpoint(base),{method:'POST',headers,body:basketBody('bad',1,selections([foreignCandidate,1]))});assert.equal(cross.status,409);});assert.deepEqual(basketCounts(state.databasePath),before);});

 test('basket families version independently, reject skips, and preserve old snapshots after later candidate revisions',async()=>{const state=await fixture();await serve(state,async(base)=>{assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:basketBody('alpha',1,selections([candidate,1]))})).status,201);assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:basketBody('beta',1,selections([candidateB,1]))})).status,201);assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:basketBody('alpha',3,selections([candidate,2]))})).status,409);assert.equal((await fetch(`${base}/owner-api/workspaces/${workspace}/candidates/${candidate}/revisions`,{method:'POST',headers,body:JSON.stringify({contractVersion:'1.0.0',expectedVersion:2,label:'Calcium v3'})})).status,201);assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:basketBody('alpha',2,selections([candidate,3]))})).status,201);assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:basketBody('beta',2,selections([candidate,1],[candidateB,1]))})).status,201);const old=await fetch(endpoint(base),{method:'POST',headers,body:basketBody('alpha',1,selections([candidate,1]))});assert.equal(old.status,200);assert.equal((await old.json() as any).basketId,basket1);});const db=new BetterSqlite3(state.databasePath);assert.deepEqual(db.prepare('SELECT basket_key basketKey,version FROM flow_candidate_baskets ORDER BY basket_key,version').all(),[{basketKey:'alpha',version:1},{basketKey:'alpha',version:2},{basketKey:'beta',version:1},{basketKey:'beta',version:2}]);assert.deepEqual(db.prepare('SELECT b.version,m.candidate_version candidateVersion,m.label FROM flow_candidate_baskets b JOIN flow_candidate_basket_members m USING(basket_id) WHERE b.basket_key=? AND m.candidate_id=? ORDER BY b.version').all('alpha',candidate),[{version:1,candidateVersion:1,label:'Calcium'},{version:2,candidateVersion:3,label:'Calcium v3'}]);db.close();});

 test('same basket key/version with changed membership is a conflict and unchanged storage',async()=>{const state=await fixture();await serve(state,async(base)=>{assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:basketBody('same',1,selections([candidate,1]))})).status,201);const before=basketCounts(state.databasePath),files=artifactFiles(state.artifactRoot);const changed=await fetch(endpoint(base),{method:'POST',headers,body:basketBody('same',1,selections([candidateB,1]))});assert.equal(changed.status,409);assert.deepEqual(basketCounts(state.databasePath),before);assert.deepEqual(artifactFiles(state.artifactRoot),files);});});

 test('concurrent differing requests for one target yield 201 and 409 with no orphan storage',async()=>{const state=await fixture();const before=basketCounts(state.databasePath),filesBefore=artifactFiles(state.artifactRoot);await serve(state,async(base)=>{const responses=await Promise.all([fetch(endpoint(base),{method:'POST',headers,body:basketBody('race',1,selections([candidate,1]))}),fetch(endpoint(base),{method:'POST',headers,body:basketBody('race',1,selections([candidateB,1]))})]);assert.deepEqual(responses.map(r=>r.status).sort(),[201,409]);});const after=basketCounts(state.databasePath);assert.equal(after.baskets-before.baskets,1);assert.equal(after.members-before.members,1);assert.equal(after.manifests-before.manifests,1);assert.equal(artifactFiles(state.artifactRoot).length-filesBefore.length,1);assert.deepEqual(fs.readdirSync(path.join(state.artifactRoot,'.owner-api-requests')),[]);});

 test('a missing target plus changed retry is generic integrity failure and never recovers bytes',async()=>{const state=await fixture();await serve(state,async(base)=>{await fetch(endpoint(base),{method:'POST',headers,body:basketBody('lost',1,selections([candidate,1]))});const db=new BetterSqlite3(state.databasePath);const {digest}=db.prepare('SELECT basket_artifact_sha256 digest FROM flow_candidate_baskets').get() as any;db.close();const target=path.join(state.artifactRoot,'sha256',digest.slice(0,2),digest);fs.rmSync(target);const before=basketCounts(state.databasePath);const response=await fetch(endpoint(base),{method:'POST',headers,body:basketBody('lost',1,selections([candidateB,1]))});assert.equal(response.status,500);assert.deepEqual(await response.json(),genericIntegrity);assert.equal(fs.existsSync(target),false);assert.deepEqual(basketCounts(state.databasePath),before);assert.deepEqual(fs.readdirSync(path.join(state.artifactRoot,'.owner-api-requests')),[]);});});

 test('basket artifact, manifest, member, and catalog drift all fail as generic integrity errors',async()=>{for(const mode of ['artifact','manifest','member','catalog'] as const){const state=await fixture();await serve(state,async(base)=>{await fetch(endpoint(base),{method:'POST',headers,body:basketBody('drift',1,selections([candidate,1]))});const db=new BetterSqlite3(state.databasePath);const row=db.prepare('SELECT basket_id basketId,basket_artifact_sha256 digest FROM flow_candidate_baskets').get() as any;if(mode==='artifact')fs.writeFileSync(path.join(state.artifactRoot,'sha256',row.digest.slice(0,2),row.digest),'private-corruption');else if(mode==='manifest'){db.pragma('foreign_keys=OFF');db.prepare('DELETE FROM artifact_manifests WHERE sha256=?').run(row.digest);}else if(mode==='member'){db.exec('DROP TRIGGER flow_candidate_basket_members_no_update');db.prepare("UPDATE flow_candidate_basket_members SET label='drifted' WHERE basket_id=?").run(row.basketId);}else{db.exec('DROP TRIGGER flow_candidate_baskets_no_update');db.prepare("UPDATE flow_candidate_baskets SET member_count=9 WHERE basket_id=?").run(row.basketId);}db.close();const response=await fetch(endpoint(base),{method:'POST',headers,body:basketBody('drift',1,selections([candidate,1]))});assert.equal(response.status,500);assert.deepEqual(await response.json(),genericIntegrity);});}});
