import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { once } from 'node:events';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import type { AddressInfo } from 'node:net';
import BetterSqlite3 from 'better-sqlite3';
import { openDatabase } from '../../src/platform/db/database.js';
import { ContentAddressedArtifactStore } from '../../src/platform/artifacts/artifact-store.js';
import { DiscoveryWorkspaceService } from '../../src/modules/flow/discovery-workspace-service.js';
import { FlowDiscoveryWorkspaceReader } from '../../src/modules/flow/discovery-workspace-reader.js';
import { ProductCandidateService } from '../../src/modules/flow/product-candidate-service.js';
import { FlowProductCandidateReader } from '../../src/modules/flow/product-candidate-reader.js';
import { CandidateBasketService } from '../../src/modules/flow/candidate-basket-service.js';
import { FlowCandidateBasketReader } from '../../src/modules/flow/candidate-basket-reader.js';
import { CandidateB7DecisionService, CANDIDATE_B7_DECISION_CAPABILITY, CANDIDATE_B7_DECISION_POLICY_ID } from '../../src/modules/governance/candidate-b7-decision-service.js';
import { createOwnerApiServer } from '../../src/api/owner-api.js';
import { createWorkspaceApiServer } from '../../src/api/workspace-api.js';

const token='correct-owner-token-with-at-least-32-characters',origin='http://127.0.0.1:5173';
const workspace='11111111-1111-4111-8111-111111111111',candidate='22222222-2222-4222-8222-111111111111',basket='33333333-3333-4333-8333-111111111111',decision='44444444-4444-4444-8444-111111111111',product='55555555-5555-4555-8555-111111111111';
const otherWorkspace='11111111-1111-4111-8111-222222222222',otherCandidate='22222222-2222-4222-8222-222222222222',otherBasket='33333333-3333-4333-8333-222222222222',otherDecision='44444444-4444-4444-8444-222222222222';
const unknown='99999999-9999-4999-8999-999999999999';
const roots:string[]=[]; test.afterEach(()=>{for(const root of roots.splice(0))fs.rmSync(root,{recursive:true,force:true});});
async function fixture(result:'PASS'|'HOLD'|'REJECT'|null='PASS'){
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'tdn-owner-product-'));roots.push(root);const databasePath=path.join(root,'db.sqlite'),artifactRoot=path.join(root,'artifacts');
  const {db}=openDatabase({databasePath});const store=new ContentAddressedArtifactStore(artifactRoot);
  const discoveries=new DiscoveryWorkspaceService({db,artifactStore:store,uuid:()=>workspace});await discoveries.createWorkspace({contractVersion:'1.0.0',workspaceKey:'calcium',title:'Thị trường canxi'});
  const candidates=new ProductCandidateService({db,artifactStore:store,uuid:()=>candidate});await candidates.createCandidate({contractVersion:'1.0.0',workspaceId:workspace,candidateKey:'adult',label:'Canxi người lớn',summary:'Ứng viên synthetic.'});
  const baskets=new CandidateBasketService({db,artifactStore:store,workspaceReader:new FlowDiscoveryWorkspaceReader(discoveries),candidateReader:new FlowProductCandidateReader(candidates),uuid:()=>basket});await baskets.freezeBasket({contractVersion:'1.0.0',workspaceId:workspace,basketKey:'shortlist',version:1,candidates:[{candidateId:candidate,candidateVersion:1}]});
  const b7=new CandidateB7DecisionService({db,artifactStore:store,basketReader:new FlowCandidateBasketReader(baskets),configuration:{policyId:CANDIDATE_B7_DECISION_POLICY_ID,policyVersion:1,requiredCapability:CANDIDATE_B7_DECISION_CAPABILITY},uuid:()=>decision,now:()=>new Date('2027-02-01T00:00:00Z')});
  if(result)await b7.decide({contractVersion:'1.0.0',basketId:basket,candidateId:candidate,candidateVersion:1,decision:result},{actorId:'owner:local',roleSnapshot:'OWNER',capabilities:new Set([CANDIDATE_B7_DECISION_CAPABILITY])});db.close();return{databasePath,artifactRoot};
}
async function addOtherPass(state:Awaited<ReturnType<typeof fixture>>){
  const {db}=openDatabase({databasePath:state.databasePath});const store=new ContentAddressedArtifactStore(state.artifactRoot);
  const discoveries=new DiscoveryWorkspaceService({db,artifactStore:store,uuid:()=>otherWorkspace});await discoveries.createWorkspace({contractVersion:'1.0.0',workspaceKey:'other-market',title:'Thị trường khác'});
  const candidates=new ProductCandidateService({db,artifactStore:store,uuid:()=>otherCandidate});await candidates.createCandidate({contractVersion:'1.0.0',workspaceId:otherWorkspace,candidateKey:'other',label:'Ứng viên khác'});
  const baskets=new CandidateBasketService({db,artifactStore:store,workspaceReader:new FlowDiscoveryWorkspaceReader(discoveries),candidateReader:new FlowProductCandidateReader(candidates),uuid:()=>otherBasket});await baskets.freezeBasket({contractVersion:'1.0.0',workspaceId:otherWorkspace,basketKey:'other-shortlist',version:1,candidates:[{candidateId:otherCandidate,candidateVersion:1}]});
  const b7=new CandidateB7DecisionService({db,artifactStore:store,basketReader:new FlowCandidateBasketReader(baskets),configuration:{policyId:CANDIDATE_B7_DECISION_POLICY_ID,policyVersion:1,requiredCapability:CANDIDATE_B7_DECISION_CAPABILITY},uuid:()=>otherDecision,now:()=>new Date('2027-02-01T01:00:00Z')});
  await b7.decide({contractVersion:'1.0.0',basketId:otherBasket,candidateId:otherCandidate,candidateVersion:1,decision:'PASS'},{actorId:'owner:local',roleSnapshot:'OWNER',capabilities:new Set([CANDIDATE_B7_DECISION_CAPABILITY])});db.close();
}
function dbDigest(databasePath:string){return createHash('sha256').update(fs.readFileSync(databasePath)).digest('hex');}
function artifactInventory(state:Awaited<ReturnType<typeof fixture>>){
  const files:string[]=[];const shaRoot=path.join(state.artifactRoot,'sha256');if(fs.existsSync(shaRoot))for(const prefix of fs.readdirSync(shaRoot))for(const name of fs.readdirSync(path.join(shaRoot,prefix)))files.push(`sha256/${prefix}/${name}`);
  const staging=path.join(state.artifactRoot,'.owner-api-requests');const staged=fs.existsSync(staging)?fs.readdirSync(staging):[];
  const db=new BetterSqlite3(state.databasePath);const manifests=(db.prepare('SELECT relative_path path FROM artifact_manifests ORDER BY relative_path').all() as {path:string}[]).map(({path})=>path);db.close();
  return{files:files.sort(),manifests,staged};
}
const headers={authorization:`Bearer ${token}`,'content-type':'application/json',origin};
const endpoint=(base:string,w=workspace,b=basket,d=decision)=>`${base}/owner-api/workspaces/${w}/candidate-baskets/${b}/b7-decisions/${d}/product-workspace`;
const body=(key='adult-calcium-product',patch:Record<string,unknown>={})=>JSON.stringify({contractVersion:'1.0.0',productWorkspaceKey:key,...patch});
async function serve(state:Awaited<ReturnType<typeof fixture>>,run:(base:string)=>Promise<void>){const api=createOwnerApiServer({...state,writeEnabled:true,token,allowedOrigin:origin,actorId:'owner:local',now:()=>new Date('2027-02-02T00:00:00Z'),uuid:()=>product});api.server.listen(0,'127.0.0.1');await once(api.server,'listening');try{await run(`http://127.0.0.1:${(api.server.address() as AddressInfo).port}`);}finally{await api.close();}}

test('OWNER creates one ACTIVE/B8 product from exact PASS and B7 read exposes verified summary',async()=>{const state=await fixture();await serve(state,async(base)=>{const response=await fetch(endpoint(base),{method:'POST',headers,body:body()});assert.equal(response.status,201);assert.deepEqual(await response.json(),{contractVersion:'1.0.0',productWorkspaceId:product,productWorkspaceKey:'adult-calcium-product',workspaceId:workspace,basketId:basket,candidateId:candidate,candidateVersion:1,b7DecisionId:decision,state:'ACTIVE',entryStep:'B8',title:'Canxi người lớn',createdAt:'2027-02-02T00:00:00.000Z',exactRetry:false});});const api=createWorkspaceApiServer(state);api.server.listen(0,'127.0.0.1');await once(api.server,'listening');try{const response=await fetch(`http://127.0.0.1:${(api.server.address() as AddressInfo).port}/api/workspaces/${workspace}/candidate-baskets/${basket}/b7`);const value=await response.json() as any;assert.equal(response.status,200);assert.deepEqual(value.candidates[0].productWorkspace,{productWorkspaceId:product,productWorkspaceKey:'adult-calcium-product',state:'ACTIVE',entryStep:'B8',title:'Canxi người lớn',createdAt:'2027-02-02T00:00:00.000Z'});assert.doesNotMatch(JSON.stringify(value),/sha256|actor|policy|capability/i);}finally{await api.close();}});

test('exact retry is literally zero total_changes; changed key conflicts; closed body and every ineligible state fail',async()=>{const state=await fixture();await serve(state,async(base)=>{assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:body()})).status,201);const db=new BetterSqlite3(state.databasePath);const before=db.prepare('SELECT total_changes() changes,(SELECT count(*) FROM flow_product_workspaces) products,(SELECT count(*) FROM artifact_manifests) manifests').get() as any;db.close();const retry=await fetch(endpoint(base),{method:'POST',headers,body:body()});assert.equal(retry.status,200);assert.equal(((await retry.json()) as any).exactRetry,true);assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:body('changed-product-key')})).status,409);assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:body('adult-calcium-product',{title:'caller title'})})).status,400);const check=new BetterSqlite3(state.databasePath);const after=check.prepare('SELECT total_changes() changes,(SELECT count(*) FROM flow_product_workspaces) products,(SELECT count(*) FROM artifact_manifests) manifests').get() as any;assert.equal(after.changes,0,'fresh verification connection observes exactly zero changes');assert.equal(after.products,before.products);assert.equal(after.manifests,before.manifests);check.close();});for(const result of ['HOLD','REJECT',null] as const){const ineligible=await fixture(result);await serve(ineligible,async(base)=>assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:body()})).status,result===null?404:409));const check=new BetterSqlite3(ineligible.databasePath);assert.equal((check.prepare('SELECT count(*) count FROM flow_product_workspaces').get() as any).count,0);check.close();}});

test('same and divergent concurrency leave one product, one manifest, and no orphan canonical or staging files',async()=>{for(const mode of ['same','divergent'] as const){const state=await fixture();const before=artifactInventory(state);await serve(state,async(base)=>{const keys=mode==='same'?['adult-calcium-product','adult-calcium-product']:['product-key-one','product-key-two'];const responses=await Promise.all(keys.map(key=>fetch(endpoint(base),{method:'POST',headers,body:body(key)})));assert.deepEqual(responses.map((response)=>response.status).sort(),mode==='same'?[200,201]:[201,409]);if(mode==='same'){const receipts=await Promise.all(responses.map((response)=>response.json() as Promise<any>));assert.deepEqual(receipts.map((receipt)=>receipt.exactRetry).sort(),[false,true]);}});const after=artifactInventory(state);const db=new BetterSqlite3(state.databasePath);assert.equal((db.prepare('SELECT count(*) count FROM flow_product_workspaces').get() as any).count,1);assert.equal(after.manifests.length,before.manifests.length+1);assert.equal(after.files.length,before.files.length+1);assert.deepEqual(after.files,after.manifests);assert.deepEqual(after.staged,[]);db.close();}});

test('exact retry recovers only an absent canonical product artifact',async()=>{const state=await fixture();await serve(state,async(base)=>{assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:body()})).status,201);const db=new BetterSqlite3(state.databasePath);const row=db.prepare('SELECT product_workspace_artifact_sha256 digest FROM flow_product_workspaces').get() as {digest:string};db.close();const file=path.join(state.artifactRoot,'sha256',row.digest.slice(0,2),row.digest);fs.unlinkSync(file);const response=await fetch(endpoint(base),{method:'POST',headers,body:body()});assert.equal(response.status,200);assert.equal(fs.existsSync(file),true);});});

test('route IDs bind exact workspace/basket/decision; auth/schema and stored corruption fail closed',async()=>{const state=await fixture();await addOtherPass(state);await serve(state,async(base)=>{assert.equal((await fetch(endpoint(base),{method:'POST',headers:{...headers,authorization:''},body:body()})).status,401);for(const ids of [['bad',basket,decision],[workspace,'bad',decision],[workspace,basket,'bad']] as const)assert.equal((await fetch(endpoint(base,...ids),{method:'POST',headers,body:body()})).status,400);assert.equal((await fetch(endpoint(base,unknown,basket,decision),{method:'POST',headers,body:body()})).status,404);assert.equal((await fetch(endpoint(base,workspace,unknown,decision),{method:'POST',headers,body:body()})).status,404);assert.equal((await fetch(endpoint(base,workspace,basket,unknown),{method:'POST',headers,body:body()})).status,404);assert.equal((await fetch(endpoint(base,otherWorkspace,basket,decision),{method:'POST',headers,body:body()})).status,409);assert.equal((await fetch(endpoint(base,workspace,otherBasket,otherDecision),{method:'POST',headers,body:body()})).status,409);assert.equal((await fetch(endpoint(base,workspace,basket,otherDecision),{method:'POST',headers,body:body()})).status,409);assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:body()})).status,201);const db=new BetterSqlite3(state.databasePath);const row=db.prepare('SELECT product_workspace_artifact_sha256 digest FROM flow_product_workspaces').get() as {digest:string};db.close();fs.writeFileSync(path.join(state.artifactRoot,'sha256',row.digest.slice(0,2),row.digest),'corrupt');assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:body()})).status,500);});const schema=JSON.parse(fs.readFileSync('contracts/api/owner-product-workspace-api.schema.json','utf8')) as any;assert.deepEqual(schema.$defs.request.required,['contractVersion','productWorkspaceKey']);assert.equal(schema.$defs.request.additionalProperties,false);assert.ok(fs.existsSync('contracts/api/owner-product-workspace-api.generated.ts'));});


test('read projections are exact, safe, decision-linked, lineage-complete, B8-empty, and byte-read-only',async()=>{const state=await fixture();await serve(state,async(base)=>assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:body()})).status,201));const before=dbDigest(state.databasePath);const api=createWorkspaceApiServer(state);api.server.listen(0,'127.0.0.1');await once(api.server,'listening');try{const base=`http://127.0.0.1:${(api.server.address() as AddressInfo).port}`;const portfolio=await (await fetch(`${base}/api/workspaces`)).json() as any;assert.equal(portfolio.workspaces[0].productCount,1);const workspaceRead=await (await fetch(`${base}/api/workspaces/${workspace}`)).json() as any;assert.deepEqual(workspaceRead.products,[{productWorkspaceId:product,productWorkspaceKey:'adult-calcium-product',state:'ACTIVE',entryStep:'B8',title:'Canxi người lớn',createdAt:'2027-02-02T00:00:00.000Z'}]);const b7=await (await fetch(`${base}/api/workspaces/${workspace}/candidate-baskets/${basket}/b7`)).json() as any;assert.equal(b7.candidates[0].decisionId,decision);assert.deepEqual(b7.candidates[0].productWorkspace,workspaceRead.products[0]);const detail=await (await fetch(`${base}/api/product-workspaces/${product}`)).json() as any;assert.deepEqual(detail,{contractVersion:'1.0.0',product:{...workspaceRead.products[0],sourceWorkspaceId:workspace,sourceBasketId:basket,sourceBasketKey:'shortlist',sourceBasketVersion:1,sourceCandidateId:candidate,sourceCandidateKey:'adult',sourceCandidateVersion:1,sourceCandidateLabel:'Canxi người lớn',sourceCandidateSummary:'Ứng viên synthetic.',sourceB7DecisionId:decision,sourceB7DecidedAt:'2027-02-01T00:00:00.000Z'},b8:{lanes:[{lane:'LEGAL',effectiveState:'NO_DECISION'},{lane:'SCIENTIFIC',effectiveState:'NO_DECISION'},{lane:'QUALITY',effectiveState:'NO_DECISION'},{lane:'FINANCE',effectiveState:'NO_DECISION'}],readyForB9:false}});for(const value of [portfolio,workspaceRead,b7,detail])assert.doesNotMatch(JSON.stringify(value),/sha256|artifact|actor|capability|policy|requestSha/i);const db=new BetterSqlite3(state.databasePath,{readonly:true});assert.equal((db.prepare('SELECT count(*) count FROM governance_product_b8_lane_decisions').get() as any).count,0);assert.equal((db.prepare('SELECT count(*) count FROM flow_b8_clearances').get() as any).count,0);db.close();}finally{await api.close();}assert.equal(dbDigest(state.databasePath),before);});

test('frozen summary/version survive later candidate revision in owner receipt and every read projection',async()=>{const state=await fixture();const {db}=openDatabase({databasePath:state.databasePath});const candidates=new ProductCandidateService({db,artifactStore:new ContentAddressedArtifactStore(state.artifactRoot)});await candidates.reviseCandidate({contractVersion:'1.0.0',candidateId:candidate,expectedVersion:1,label:'Canxi người lớn v2',summary:'Tóm tắt sửa sau snapshot.'});db.close();await serve(state,async(base)=>{const receipt=await (await fetch(endpoint(base),{method:'POST',headers,body:body()})).json() as any;assert.equal(receipt.candidateVersion,1);assert.equal(receipt.title,'Canxi người lớn');});const api=createWorkspaceApiServer(state);api.server.listen(0,'127.0.0.1');await once(api.server,'listening');try{const base=`http://127.0.0.1:${(api.server.address() as AddressInfo).port}`;const b7=await (await fetch(`${base}/api/workspaces/${workspace}/candidate-baskets/${basket}/b7`)).json() as any;assert.deepEqual([b7.candidates[0].candidateVersion,b7.candidates[0].label,b7.candidates[0].summary],[1,'Canxi người lớn','Ứng viên synthetic.']);const detail=await (await fetch(`${base}/api/product-workspaces/${product}`)).json() as any;assert.deepEqual([detail.product.sourceCandidateVersion,detail.product.sourceCandidateLabel,detail.product.sourceCandidateSummary],[1,'Canxi người lớn','Ứng viên synthetic.']);}finally{await api.close();}});

test('same key reused for a different exact PASS decision conflicts without healing or artifacts',async()=>{const state=await fixture();await addOtherPass(state);await serve(state,async(base)=>{assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:body()})).status,201);const before=artifactInventory(state);const response=await fetch(endpoint(base,otherWorkspace,otherBasket,otherDecision),{method:'POST',headers,body:body()});assert.equal(response.status,409);assert.deepEqual(artifactInventory(state),before);});});

test('recovery heals missing exact target only; corrupt, existing, manifest drift, and upstream failure stay closed',async()=>{for(const mode of ['corrupt','manifest','upstream'] as const){const state=await fixture();await serve(state,async(base)=>{assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:body()})).status,201);const db=new BetterSqlite3(state.databasePath);const row=db.prepare('SELECT product_workspace_artifact_sha256 digest FROM flow_product_workspaces').get() as {digest:string};const productPath=path.join(state.artifactRoot,'sha256',row.digest.slice(0,2),row.digest);if(mode==='corrupt')fs.writeFileSync(productPath,'corrupt');if(mode==='manifest'){fs.unlinkSync(productPath);db.prepare('UPDATE artifact_manifests SET media_type=? WHERE sha256=?').run('text/plain',row.digest);}if(mode==='upstream'){fs.unlinkSync(productPath);const source=db.prepare('SELECT decision_artifact_sha256 digest FROM governance_candidate_b7_decisions').get() as {digest:string};fs.writeFileSync(path.join(state.artifactRoot,'sha256',source.digest.slice(0,2),source.digest),'corrupt');}db.close();const before=artifactInventory(state);assert.equal((await fetch(endpoint(base),{method:'POST',headers,body:body()})).status,500);assert.deepEqual(artifactInventory(state),before);if(mode!=='corrupt')assert.equal(fs.existsSync(productPath),false);});}});

test('protected Task028 service and migration hashes remain unchanged',()=>{assert.equal(createHash('sha256').update(fs.readFileSync('src/modules/flow/product-workspace-service.ts')).digest('hex'),'1c7d1e8c23ae6eb43b23410ac4bbb486bde1649b92576559082f7b19c8319d3b');assert.equal(createHash('sha256').update(fs.readFileSync('migrations/0016_product_workspaces.sql')).digest('hex'),'9e8daf707e2a913d60610690fcab57c178f2facd0883e45bc53dd72a30284c72');});
