import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, test } from 'node:test';
import type { LockedStpArtifact } from '../../contracts/flow/locked-stp-artifact.generated.js';
import type { ProductB10Decision } from '../../contracts/governance/product-b10-decision.generated.js';
import type { ProductB10DecisionRequest } from '../../contracts/governance/product-b10-decision-request.generated.js';
import type { LockedStpReader } from '../../src/modules/flow/index.js';
import { canonicalJson } from '../../src/modules/foundation/index.js';
import {
  GovernanceProductB10Reader,
  GovernanceValidationError,
  PRODUCT_B10_REVIEW_CAPABILITY,
  ProductB10DecisionIdentityConflictError,
  ProductB10DecisionService,
} from '../../src/modules/governance/index.js';
import { ContentAddressedArtifactStore } from '../../src/platform/artifacts/index.js';
import { openDatabase } from '../../src/platform/db/index.js';

const roots: string[] = [];
afterEach(async () => Promise.all(roots.splice(0).map((root) => fsp.rm(root, { recursive: true, force: true }))));
const lockId='99999999-9999-4999-8999-999999999992';
const workspaceId='66666666-6666-4666-8666-666666666666';
const ids=['aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa4'];
const owner={actorId:'owner:khang',roleSnapshot:'OWNER',capabilities:new Set<string>([PRODUCT_B10_REVIEW_CAPABILITY])};
function locked():LockedStpArtifact{return {contractVersion:'1.0.0',lockId,state:'LOCKED_STP',lockedAt:'2026-10-01T00:00:01.000Z',requestSha256:'1'.repeat(64),workingStp:{workingStpId:'99999999-9999-4999-8999-999999999991',workingDigest:'2'.repeat(64),content:{segments:[{key:'active-adults',label:'Người trưởng thành năng động'},{key:'older-adults',label:'Người lớn tuổi'}],primaryTargetSegmentKey:'active-adults',secondaryTargetSegmentKeys:['older-adults'],positioningStatement:'Canxi tiện dùng cho người trưởng thành chủ động.'}},productWorkspace:{productWorkspaceArtifactSha256:'3'.repeat(64),artifact:{contractVersion:'1.0.0',productWorkspaceId:workspaceId,productWorkspaceKey:'adult-calcium-product',state:'ACTIVE',entryStep:'B8',title:'Canxi người lớn tổng hợp',createdAt:'2026-09-28T00:00:00.000Z',requestSha256:'4'.repeat(64),source:{discoveryWorkspace:{workspaceId:'11111111-1111-4111-8111-111111111111'},basket:{basketId:'44444444-4444-4444-8444-444444444444',basketArtifactSha256:'5'.repeat(64),workspaceId:'11111111-1111-4111-8111-111111111111',basketKey:'b7-basket',basketVersion:1},candidate:{candidateId:'22222222-2222-4222-8222-222222222222',candidateVersion:1,candidateArtifactSha256:'6'.repeat(64),candidateKey:'adult-calcium',label:'Canxi người lớn tổng hợp',summary:'Ý tưởng tổng hợp.',state:'EXPLORING'},b7Decision:{contractVersion:'1.0.0',decisionId:'55555555-5555-4555-8555-555555555555',decisionArtifactSha256:'7'.repeat(64),decidedAt:'2026-09-27T00:00:00.000Z',decision:'PASS',actor:{actorId:'owner:khang',roleSnapshot:'OWNER'},requiredCapability:'governance:candidate-b7-review',policy:{policyId:'governance:candidate-b7-review-v1',policyVersion:1},requestSha256:'8'.repeat(64)}}}},b8Clearance:{clearanceId:'88888888-8888-4888-8888-888888888888',clearanceArtifactSha256:'9'.repeat(64),state:'READY_FOR_B9'},actor:{actorId:'owner:khang',roleSnapshot:'OWNER'},requiredCapability:'governance:product-b9-lock',policy:{policyId:'governance:product-b9-lock-v1',policyVersion:1}};}
class Source implements LockedStpReader{artifact=locked();calls:string[]=[];async readVerifiedLockedStp(id:string){this.calls.push(id);return structuredClone(this.artifact);}}
function req(decision:ProductB10DecisionRequest['decision'],previousDecisionId:string|null=null,overrides:Partial<ProductB10DecisionRequest>={}):ProductB10DecisionRequest{return {contractVersion:'1.0.0',lockedStpId:lockId,previousDecisionId,decision,...overrides};}
function digest(value:unknown){return createHash('sha256').update(Buffer.from(canonicalJson(value))).digest('hex');}
function setup(source=new Source(),dbPath?:string){const root=dbPath?path.dirname(dbPath):fs.mkdtempSync(path.join(os.tmpdir(),'tdn-b10-'));if(!dbPath)roots.push(root);const opened=openDatabase({databasePath:dbPath??path.join(root,'db.sqlite')});const artifacts=new ContentAddressedArtifactStore(path.join(root,'artifacts'));let u=0,t=0;const service=new ProductB10DecisionService({db:opened.db,artifactStore:artifacts,lockedStpReader:source,uuid:()=>ids[u++]!,now:()=>new Date(Date.UTC(2026,9,2,0,0,t++))});return{root,db:opened.db,artifacts,source,service};}
function count(state:ReturnType<typeof setup>,table:string){return(state.db.prepare(`SELECT count(*) n FROM ${table}`).get()as{n:bigint}).n;}

for(const decision of ['APPROVE','HOLD','REJECT'] as const)test(`exact verified LOCKED_STP accepts ${decision} as first decision with null predecessor`,async()=>{const state=setup();const result=await state.service.decide(req(decision),owner);const replay=await state.service.replay(result.decisionId);assert.equal(result.decisionNumber,1);assert.equal(replay.previousDecisionId,null);assert.equal(replay.decision,decision);assert.equal(replay.lockedStp.lockId,lockId);assert.equal(replay.lockedStp.lockArtifactSha256,digest(locked()));assert.deepEqual(replay.lockedStp.artifact,locked());assert.equal(replay.productWorkspaceId,workspaceId);assert.equal(count(state,'governance_product_b10_decisions'),1n);state.db.close();});

test('first decision requires null; malformed, missing, wrong-lock, wrong-workspace and wrong identity fail closed',async()=>{for(const mutate of [(s:Source)=>{},(s:Source)=>{s.artifact={...locked(),lockId:ids[3]!};},(s:Source)=>{s.artifact={...locked(),state:'BROKEN' as 'LOCKED_STP'};},(s:Source)=>{s.artifact={...locked(),productWorkspace:{...locked().productWorkspace,artifact:{...locked().productWorkspace.artifact,productWorkspaceId:ids[3]!}}};}] ){const source=new Source();mutate(source);const state=setup(source);await assert.rejects(state.service.decide(req('APPROVE',ids[0]!),owner));assert.equal(count(state,'governance_product_b10_decisions'),0n);state.db.close();}const state=setup();await assert.rejects(state.service.decide(req('APPROVE',null,{lockedStpId:ids[3]!}),owner));assert.equal(count(state,'governance_product_b10_decisions'),0n);state.db.close();});

test('every effective state can correct to either other state; numbers and predecessors are exact and historical decisions replay',async()=>{for(const firstValue of ['APPROVE','HOLD','REJECT'] as const)for(const secondValue of ['APPROVE','HOLD','REJECT'] as const){if(firstValue===secondValue)continue;const state=setup();const first=await state.service.decide(req(firstValue),owner);const second=await state.service.decide(req(secondValue,first.decisionId),owner);assert.equal(second.decisionNumber,2);assert.equal((await state.service.replay(first.decisionId)).decision,firstValue);assert.equal((await state.service.replay(second.decisionId)).previousDecisionId,first.decisionId);assert.equal((await state.service.readStatusByLockedStp(lockId)).decisionExists,true);state.db.close();}});

test('repeating effective state, stale/missing/wrong predecessor fail closed',async()=>{const state=setup();const first=await state.service.decide(req('HOLD'),owner);await assert.rejects(state.service.decide(req('HOLD',first.decisionId),owner),GovernanceValidationError);await assert.rejects(state.service.decide(req('APPROVE',null),owner),ProductB10DecisionIdentityConflictError);const second=await state.service.decide(req('APPROVE',first.decisionId),owner);await assert.rejects(state.service.decide(req('REJECT',first.decisionId),owner),ProductB10DecisionIdentityConflictError);await assert.rejects(state.service.decide(req('REJECT',ids[3]!),owner),ProductB10DecisionIdentityConflictError);assert.equal(second.decisionNumber,2);assert.equal(count(state,'governance_product_b10_decisions'),2n);state.db.close();});

test('exact retries return same decision identity with zero mutations, including historical retry without live B9',async()=>{const state=setup();const input=req('HOLD');const first=await state.service.decide(input,owner);const before=(state.db.prepare('SELECT total_changes() n').get()as{n:bigint}).n;const retry=await state.service.decide(input,owner);assert.deepEqual(retry,{...first,deduplicated:true,databaseMutations:0});assert.equal((state.db.prepare('SELECT total_changes() n').get()as{n:bigint}).n,before);await state.service.decide(req('APPROVE',first.decisionId),owner);state.source.readVerifiedLockedStp=async()=>{throw new Error('B9 unavailable');};const historicalRetry=await state.service.decide(input,owner);assert.equal(historicalRetry.decisionId,first.decisionId);assert.equal(historicalRetry.databaseMutations,0);assert.equal((await state.service.replay(first.decisionId)).decision,'HOLD');state.db.close();});

test('closed request and OWNER capability boundary reject unknown financial/free-text/AI fields and unauthorized actors before writes',async()=>{for(const extra of ['reason','rationale','note','explanation','budget','amount','currency','fundingCeiling','fundingPeriod','disbursementSchedule','aiRecommendation']){const state=setup();await assert.rejects(state.service.decide({...req('APPROVE'),[extra]:'forbidden'},owner),GovernanceValidationError);assert.equal(state.source.calls.length,0);assert.equal(count(state,'governance_product_b10_decisions'),0n);state.db.close();}for(const actor of [{...owner,roleSnapshot:'SPECIALIST'},{...owner,roleSnapshot:'REVIEWER'},{...owner,roleSnapshot:'AI',actorId:'ai:agent'},{...owner,roleSnapshot:'SERVICE',actorId:'service:worker'},{...owner,capabilities:new Set<string>()}]){const state=setup();await assert.rejects(state.service.decide(req('APPROVE'),actor),GovernanceValidationError);assert.equal(state.source.calls.length,0);assert.equal(count(state,'governance_product_b10_decisions'),0n);state.db.close();}});

test('effective readers return newest only and readyForB11 only for APPROVE without creating B11',async()=>{const state=setup();assert.deepEqual(await state.service.readStatusByLockedStp(lockId),{lockedStpId:lockId,productWorkspaceId:workspaceId,decisionExists:false,readyForB11:false});assert.deepEqual(await state.service.readStatusByProductWorkspace(workspaceId),{productWorkspaceId:workspaceId,decisionExists:false,readyForB11:false});const first=await state.service.decide(req('HOLD'),owner);const approve=await state.service.decide(req('APPROVE',first.decisionId),owner);const status=await new GovernanceProductB10Reader(state.service).readStatusByProductWorkspace(workspaceId);assert.deepEqual(status,{lockedStpId:lockId,productWorkspaceId:workspaceId,decisionExists:true,effectiveDecisionId:approve.decisionId,effectiveDecisionNumber:2,effectiveDecision:'APPROVE',readyForB11:true});const reject=await state.service.decide(req('REJECT',approve.decisionId),owner);const rejectedStatus=await state.service.readStatusByLockedStp(lockId);assert.equal(rejectedStatus.readyForB11,false);assert.equal(rejectedStatus.decisionExists,true);if(!rejectedStatus.decisionExists)assert.fail('expected effective B10 decision');assert.equal(rejectedStatus.effectiveDecisionId,reject.decisionId);assert.equal((state.db.prepare("SELECT count(*) n FROM sqlite_master WHERE type='table' AND name LIKE '%b11%'").get()as{n:bigint}).n,0n);state.db.close();});

test('separate SQLite connections serialize same-predecessor corrections so only one succeeds',async()=>{const state=setup();const first=await state.service.decide(req('HOLD'),owner);const secondDb=openDatabase({databasePath:path.join(state.root,'db.sqlite')}).db;const second=new ProductB10DecisionService({db:secondDb,artifactStore:state.artifacts,lockedStpReader:state.source,uuid:()=>ids[2]!,now:()=>new Date('2026-10-02T00:00:02Z')});const results=await Promise.allSettled([state.service.decide(req('APPROVE',first.decisionId),owner),second.decide(req('REJECT',first.decisionId),owner)]);assert.equal(results.filter(result=>result.status==='fulfilled').length,1);assert.equal(results.filter(result=>result.status==='rejected').length,1);assert.equal(count(state,'governance_product_b10_decisions'),2n);assert.equal(count(state,'artifact_manifests'),2n);const artifactFiles=fs.readdirSync(path.join(state.root,'artifacts','sha256'),{recursive:true,withFileTypes:true}).filter(entry=>entry.isFile());assert.equal(artifactFiles.length,2);assert.deepEqual(state.db.prepare('SELECT decision_number n FROM governance_product_b10_decisions ORDER BY decision_number').all(),[{n:1n},{n:2n}]);secondDb.close();state.db.close();});

test('database prevents skipped sequence, wrong predecessor lineage, repeated state, update and delete',async()=>{const state=setup();const first=await state.service.decide(req('HOLD'),owner);const row=state.db.prepare('SELECT * FROM governance_product_b10_decisions WHERE decision_id=?').get(first.decisionId)as Record<string,unknown>;const insert=state.db.prepare(`INSERT INTO governance_product_b10_decisions(decision_id,locked_stp_id,locked_stp_artifact_sha256,product_workspace_id,decision_number,previous_decision_id,decision,actor_id,role_snapshot,required_capability,policy_id,policy_version,request_sha256,decision_artifact_sha256,decided_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);assert.throws(()=>insert.run(ids[2],row.locked_stp_id,row.locked_stp_artifact_sha256,row.product_workspace_id,3,first.decisionId,'APPROVE',row.actor_id,row.role_snapshot,row.required_capability,row.policy_id,row.policy_version,'a'.repeat(64),row.decision_artifact_sha256,row.decided_at),/chain_invalid/);assert.throws(()=>insert.run(ids[2],row.locked_stp_id,row.locked_stp_artifact_sha256,row.product_workspace_id,2,first.decisionId,'HOLD',row.actor_id,row.role_snapshot,row.required_capability,row.policy_id,row.policy_version,'b'.repeat(64),row.decision_artifact_sha256,row.decided_at),/chain_invalid/);assert.throws(()=>state.db.prepare("UPDATE governance_product_b10_decisions SET decision='APPROVE'").run(),/immutable/);assert.throws(()=>state.db.prepare('DELETE FROM governance_product_b10_decisions').run(),/immutable/);state.db.close();});

test('replay rejects missing, corrupt, noncanonical, metadata, row, lock and predecessor mismatches',async()=>{for(const mode of ['missing','corrupt','noncanonical','metadata','row','lock','predecessor']as const){const source=new Source();const state=setup(source);const first=await state.service.decide(req('HOLD'),owner);const second=mode==='predecessor'?await state.service.decide(req('APPROVE',first.decisionId),owner):first;const artifactPath=state.artifacts.pathForDigest(second.decisionArtifactSha256);if(mode==='missing')fs.unlinkSync(artifactPath);if(mode==='corrupt')fs.writeFileSync(artifactPath,'{}');if(mode==='noncanonical'){const data=Buffer.from(JSON.stringify(JSON.parse(fs.readFileSync(artifactPath,'utf8')),null,2));const sha=createHash('sha256').update(data).digest('hex');const target=state.artifacts.pathForDigest(sha);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,data);state.db.exec('DROP TRIGGER governance_product_b10_decisions_no_update');state.db.prepare("INSERT INTO artifact_manifests SELECT ?,?,media_type,?,acquired_at,contract_version,retention_status,created_at FROM artifact_manifests WHERE sha256=?").run(sha,data.length,`sha256/${sha.slice(0,2)}/${sha}`,second.decisionArtifactSha256);state.db.prepare('UPDATE governance_product_b10_decisions SET decision_artifact_sha256=? WHERE decision_id=?').run(sha,second.decisionId);}if(mode==='metadata')state.db.prepare('UPDATE artifact_manifests SET retention_status=? WHERE sha256=?').run('held',second.decisionArtifactSha256);if(mode==='row'){state.db.exec('DROP TRIGGER governance_product_b10_decisions_no_update');state.db.prepare("UPDATE governance_product_b10_decisions SET actor_id='owner:other' WHERE decision_id=?").run(second.decisionId);}if(mode==='lock'){state.db.exec('DROP TRIGGER governance_product_b10_decisions_no_update');state.db.prepare("UPDATE governance_product_b10_decisions SET locked_stp_artifact_sha256=? WHERE decision_id=?").run('f'.repeat(64),second.decisionId);}if(mode==='predecessor'){state.db.exec('DROP TRIGGER governance_product_b10_decisions_no_update');state.db.prepare('UPDATE governance_product_b10_decisions SET previous_decision_id=? WHERE decision_id=?').run(ids[3],second.decisionId);}await assert.rejects(state.service.replay(second.decisionId));state.db.close();}});

test('reused decision artifact preserves first-storage acquired_at and non-active manifests fail closed',async()=>{for(const retention of ['active','held']as const){const state=setup();const input=req('APPROVE');const actor={actorId:'owner:khang',roleSnapshot:'OWNER' as const};const requestSha=digest({request:input,actor,requiredCapability:'governance:product-b10-review',policy:{policyId:'governance:product-b10-review-v1',policyVersion:1},lockedStpArtifactSha256:digest(locked()),productWorkspaceId:workspaceId});const artifact:ProductB10Decision={contractVersion:'1.0.0',decisionId:ids[0]!,decisionNumber:1,previousDecisionId:null,decision:'APPROVE',decidedAt:'2026-10-02T00:00:00.000Z',lockedStp:{lockId,lockArtifactSha256:digest(locked()),artifact:locked()},productWorkspaceId:workspaceId,actor,requiredCapability:'governance:product-b10-review',policy:{policyId:'governance:product-b10-review-v1',policyVersion:1},requestSha256:requestSha};const stored=await state.artifacts.put(Buffer.from(canonicalJson(artifact)));state.db.prepare("INSERT INTO artifact_manifests VALUES(?,?,'application/json',?,'2000-01-01T00:00:00.000Z','1.0.0',?,'2000-01-01T00:00:00.000Z')").run(stored.sha256,stored.byteSize,stored.relativePath,retention);if(retention==='active'){await state.service.decide(input,owner);assert.equal((state.db.prepare('SELECT acquired_at value FROM artifact_manifests WHERE sha256=?').get(stored.sha256)as{value:string}).value,'2000-01-01T00:00:00.000Z');}else{await assert.rejects(state.service.decide(input,owner),ProductB10DecisionIdentityConflictError);assert.equal(count(state,'governance_product_b10_decisions'),0n);}state.db.close();}});

test('migration v19→v20 and idempotent rerun pass; 0001–0019 are byte-identical; no Box 4 SQL/FK or B11',()=>{const names=fs.readdirSync('migrations').filter(name=>/^00(?:0[1-9]|1[0-9])_/.test(name)).sort();assert.equal(names.length,19);for(const name of names){const current=fs.readFileSync(path.join('migrations',name));const base=fs.readFileSync(path.join('/home/pkhang/.nanobot/workspace/tdn-growth-os-task-031/migrations',name));assert.deepEqual(current,base);}const root=fs.mkdtempSync(path.join(os.tmpdir(),'tdn-b10-migration-'));roots.push(root);const dir=path.join(root,'migrations');fs.mkdirSync(dir);for(const name of names)fs.copyFileSync(path.join('migrations',name),path.join(dir,name));const dbPath=path.join(root,'db.sqlite');const v19=openDatabase({databasePath:dbPath,migrationsDirectory:dir});assert.equal(v19.migration.currentVersion,19);v19.db.close();fs.copyFileSync('migrations/0020_combined_b10_decisions.sql',path.join(dir,'0020_combined_b10_decisions.sql'));const v20=openDatabase({databasePath:dbPath,migrationsDirectory:dir});assert.deepEqual(v20.migration.applied,[20]);v20.db.close();const rerun=openDatabase({databasePath:dbPath,migrationsDirectory:dir});assert.deepEqual(rerun.migration.applied,[]);assert.equal(rerun.migration.currentVersion,20);assert.equal((rerun.db.prepare("SELECT count(*) n FROM sqlite_master WHERE type='table' AND name LIKE '%b11%'").get()as{n:bigint}).n,0n);rerun.db.close();for(const file of ['migrations/0020_combined_b10_decisions.sql','src/modules/governance/product-b10-decision-service.ts']){const text=fs.readFileSync(file,'utf8');assert.doesNotMatch(text,/flow_locked_stps|flow_stp_working|flow_b8_clearance|flow_product_workspace|governance_product_b8|governance_candidate_b7/i);assert.doesNotMatch(text,/REFERENCES\s+(?:flow_|governance_)/i);}});

test('synthetic decisions/corrections leave all B7/B8/clearance/STP tables unchanged and create no B11 or external action',async()=>{const state=setup();const tables=['governance_candidate_b7_decisions','flow_product_workspaces','governance_product_b8_lane_decisions','flow_b8_clearances','flow_stp_working_records','flow_locked_stps']as const;const before=Object.fromEntries(tables.map(table=>[table,count(state,table)]));const first=await state.service.decide(req('HOLD'),owner);const approve=await state.service.decide(req('APPROVE',first.decisionId),owner);const reject=await state.service.decide(req('REJECT',approve.decisionId),owner);assert.equal(reject.decisionNumber,3);for(const table of tables)assert.equal(count(state,table),before[table]);assert.equal(count(state,'governance_product_b10_decisions'),3n);assert.equal((state.db.prepare("SELECT count(*) n FROM sqlite_master WHERE type='table' AND (name LIKE '%b11%' OR name LIKE '%task%' OR name LIKE '%notification%' OR name LIKE '%payment%')").get()as{n:bigint}).n,0n);state.db.close();});

test('historical and effective replay use frozen lock after B9 reader changes or becomes unavailable',async()=>{const state=setup();const first=await state.service.decide(req('HOLD'),owner);const second=await state.service.decide(req('APPROVE',first.decisionId),owner);state.source.artifact={...locked(),lockedAt:'2027-01-01T00:00:00Z'};assert.equal((await state.service.replay(first.decisionId)).lockedStp.artifact.lockedAt,'2026-10-01T00:00:01.000Z');state.source.readVerifiedLockedStp=async()=>{throw new Error('unavailable');};assert.equal((await state.service.replay(second.decisionId)).decision,'APPROVE');const status=await state.service.readStatusByLockedStp(lockId);assert.equal(status.decisionExists,true);if(!status.decisionExists)assert.fail('expected effective B10 decision');assert.equal(status.effectiveDecisionId,second.decisionId);state.db.close();});

test('later descendant replay validates the complete predecessor chain',async()=>{const state=setup();const first=await state.service.decide(req('HOLD'),owner);const second=await state.service.decide(req('APPROVE',first.decisionId),owner);const third=await state.service.decide(req('REJECT',second.decisionId),owner);state.db.exec('DROP TRIGGER governance_product_b10_decisions_no_update');state.db.prepare('UPDATE governance_product_b10_decisions SET previous_decision_id=? WHERE decision_id=?').run(ids[3],second.decisionId);await assert.rejects(state.service.replay(third.decisionId),ProductB10DecisionIdentityConflictError);state.db.close();});
