import privateSourceSchema from '../../../../contracts/analysis/private-insight-source-projection.schema.json' with { type: 'json' };
import { registerPrivateReviewSchemas } from './private-review-contracts.js';
import { createRequire } from 'node:module';
import located from '../../../../contracts/analysis/located-insight-methods.schema.json' with { type: 'json' };
import selection from '../../../../contracts/analysis/automation-insight-selection.schema.json' with { type: 'json' };
import coding from '../../../../contracts/analysis/automation-insight-coding.schema.json' with { type: 'json' };
import model from '../../../../contracts/analysis/automation-insight-model.schema.json' with { type: 'json' };
import classified from '../../../../contracts/analysis/automation-classified-report-revision.schema.json' with { type: 'json' };
import revision from '../../../../contracts/analysis/automation-insight-report-revision.schema.json' with { type: 'json' };
import schema from '../../../../contracts/analysis/automation-insight-crosscheck.schema.json' with { type: 'json' };
import api from '../../../../contracts/api/research-automation-insight-crosscheck-api.schema.json' with { type: 'json' };
import type { InsightCrosscheckRequest, InsightCrosscheckSource, InsightCrosscheckBlindedInput, InsightCrosscheckPrompt, InsightCrosscheckCandidates, InsightCrosscheckSnapshot } from '../../../../contracts/analysis/automation-insight-crosscheck.generated.js';
import type { InsightModelConfiguration } from '../../../../contracts/analysis/automation-insight-model.generated.js';
import type { ResearchInsightCrosscheckResponse } from '../../../../contracts/api/research-automation-insight-crosscheck-api.generated.js';
const require = createRequire(import.meta.url);
const { Ajv2020 } = require('ajv/dist/2020.js') as typeof import('ajv/dist/2020.js');
const ajv = new Ajv2020({ strict: true, allErrors: false });
(require('ajv-formats') as typeof import('ajv-formats')).default(ajv);
registerPrivateReviewSchemas(ajv); ajv.addSchema(privateSourceSchema);
for (const contract of [located, selection, coding, model, classified, revision, schema, api]) ajv.addSchema(contract);
const ref = (name: string) => ({ $ref: `${schema.$id}#/$defs/${name}` });
export const crosscheckRequestValid = ajv.compile<InsightCrosscheckRequest>(ref('request'));
export const crosscheckSourceValid = ajv.compile<InsightCrosscheckSource>(ref('source'));
export const crosscheckInputValid = ajv.compile<InsightCrosscheckBlindedInput>(ref('input'));
export const crosscheckPromptValid = ajv.compile<InsightCrosscheckPrompt>(ref('prompt'));
export const crosscheckCandidatesValid = ajv.compile<InsightCrosscheckCandidates>(ref('candidates'));
export const crosscheckSnapshotValid = ajv.compile<InsightCrosscheckSnapshot>(ref('snapshot'));
export const crosscheckConfigurationValid = ajv.compile<InsightModelConfiguration>({ $ref: `${model.$id}#/$defs/configuration` });
export const crosscheckResponseValid = ajv.compile<ResearchInsightCrosscheckResponse>({ $ref: `${api.$id}#/$defs/response` });
