import type { ResearchReviewCorpus } from '../../../../contracts/analysis/research-review-corpus.generated.js';
import { escapeHtml as escape } from './descriptive-report.js';

/** Literal source inventory, deliberately not customer coding or an Insight conclusion. */
export function reviewCorpusSection(corpus: ResearchReviewCorpus, id: 'I03' | 'I17'): string {
  const c = corpus.coverage;
  const warning = `<p class="warning">${corpus.capture.mode === 'fixture' ? 'Dữ liệu synthetic dùng kiểm thử. ' : ''}Review cấp listing, chưa xác nhận đúng variant. Kỳ báo cáo không lọc ngày review. Chưa coding; số dòng không phải số khách hàng, tỷ lệ chủ đề hay độ phủ toàn thị trường. Metadata tác giả không được đưa vào báo cáo; nội dung tự do vẫn có thể chứa thông tin cá nhân.</p>`;
  if (id === 'I03') return warning + `<dl><dt>Dòng nguồn</dt><dd>${c.rawRows}</dd><dt>Dòng đúng listing đã chọn</dt><dd>${c.selectedListingRawRows}</dd><dt>Dòng tách riêng</dt><dd>${c.quarantinedRawRows}</dd><dt>Dòng có chữ đọc được</dt><dd>${c.readableRawRows} (toàn tập thu, gồm dòng tách riêng)</dd><dt>Dòng trùng đồng nhất đã gộp</dt><dd>${c.collapsedEqualDuplicateRows}</dd><dt>Nhóm ID có nội dung mâu thuẫn</dt><dd>${c.conflictingRecordGroups}</dd><dt>Dòng có rating không hợp lệ</dt><dd>${c.invalidRatingRawRows} (không tự bỏ phần chữ)</dd><dt>Phân tích chủ đề</dt><dd>Chưa coding, chưa có mẫu số chủ đề</dd></dl><p>Cần nối codebook và phương pháp located coding vào corpus trước khi kết luận về hành vi, động cơ, nhu cầu hay tỷ lệ chủ đề.</p>`;
  const rows = corpus.records.flatMap(record => record.versions.map(version => {
    const state = record.disposition === 'QUARANTINED' ? 'Tách riêng: không đủ nhận diện listing đã chọn' : record.disposition === 'UNRESOLVED_CONFLICT' ? 'Chưa xử lý: cùng ID nhưng khác nội dung' : 'Nguồn thô, chưa coding';
    return `<tr><td>${escape(record.identity.listingKey ?? 'Chưa rõ listing')}<br>${escape(state)}</td><td><blockquote style="white-space:pre-wrap;overflow-wrap:anywhere">${version.textState === 'READABLE' ? escape(version.text ?? '') : version.textState === 'EMPTY' ? 'Nguồn không có phần chữ' : 'Phần chữ không đọc được'}</blockquote></td><td>${version.rating.state === 'VALID' ? `${version.rating.value}/5` : version.rating.state === 'MISSING' ? 'Thiếu rating' : 'Rating không hợp lệ'}</td><td>${version.sourceRefs.map(ref => `<code>${escape(ref.pageSha256)}</code><br>${escape(ref.textPointer ?? ref.rowPointer)}`).join('<hr>')}</td></tr>`;
  })).join('');
  return warning + `<p>Collection: <code>${escape(corpus.collectionSha256)}</code>. Mapping: ${escape(corpus.mappingRevision)}. Mỗi quote trỏ đến đúng page digest và JSON pointer; mọi lần xuất lại giữ nguyên phiên bản này.</p><div class="table-wrap"><table><caption>Toàn bộ nhóm bản ghi đã thu, gồm dòng tách riêng và nội dung mâu thuẫn; không dùng chúng như một tập đã coding.</caption><thead><tr><th>Listing / trạng thái</th><th>Nguyên văn</th><th>Rating nguồn</th><th>Vị trí nguồn</th></tr></thead><tbody>${rows || '<tr><td colspan="4">Collection đã lưu nhưng không có dòng review. Không suy ra khách hàng không có phản hồi.</td></tr>'}</tbody></table></div>`;
}
