/** Report registry v1.9. This is independent of board/connector readiness: S19 is graded by the original page, S25 stays mixed. */
export const REPORT_SOURCE_REGISTRY = {
  S01: ['C', 'dữ liệu bán hàng ước tính trên sàn', 'SALES_MARKET'],
  S02: ['C', 'dữ liệu video bán hàng (ước tính)', 'SALES_MARKET'],
  S03: ['C', 'dữ liệu thương mại ước tính', 'SALES_MARKET'],
  S04: ['B', 'trang bán của người bán', 'SELLER_VOICE'],
  S05: ['B', 'review công khai trên Shopee', 'CUSTOMER_VOICE'],
  S06: ['B', 'review công khai trên TikTok Shop', 'CUSTOMER_VOICE'],
  S07: ['B', 'bình luận công khai dưới video', 'CUSTOMER_VOICE'],
  S08: ['B', 'bài viết công khai trên Facebook', 'CUSTOMER_VOICE'],
  S09: ['B', 'bài viết công khai trên Instagram', 'CUSTOMER_VOICE'],
  S10: ['B', 'bài viết công khai trên X', 'CUSTOMER_VOICE'],
  S11: ['B', 'bình luận công khai trên YouTube', 'CUSTOMER_VOICE'],
  S12: ['A', 'dữ liệu của shop', 'CUSTOMER_VOICE'],
  S13: ['C', 'bài hướng dẫn công khai', 'CUSTOMER_VOICE'],
  S14: ['B', 'nội dung video của người bán', 'SELLER_VOICE'],
  S15: ['B', 'thư viện quảng cáo công khai của Meta', 'SELLER_VOICE'],
  S16: ['B', 'thư viện quảng cáo nổi bật của TikTok', 'SELLER_VOICE'],
  S17: ['B', 'thư viện quảng cáo công khai của Google', 'SELLER_VOICE'],
  S18: ['B', 'trang thương hiệu trên Facebook', 'SELLER_VOICE'],
  S19: [null, 'kết quả tìm kiếm Google', 'DOCUMENTS'],
  S20: ['B', 'mức quan tâm tìm kiếm trên Google', 'SALES_MARKET'],
  S21: ['A', 'Cục Thống kê (nso.gov.vn)', 'MACRO'],
  S22: ['A', 'Cục Thống kê (nso.gov.vn)', 'MACRO'],
  S23: ['A', 'Ngân hàng Thế giới (World Bank Open Data)', 'MACRO'],
  S24: ['A', 'Cơ sở dữ liệu thương mại của Liên Hợp Quốc', 'MACRO'],
  S25: [null, 'báo cáo đã công bố của …', 'DOCUMENTS'],
  S26: ['C', 'tin đã đăng trên …', 'DOCUMENTS'],
  S27: ['C', 'bản quét review gian hàng của bên thứ ba', 'CUSTOMER_VOICE'],
} as const;
