import { useState } from 'react';
import type { B10Decision, Product } from './model';
import { ownerB10Disabled, OwnerWriteError, submitOwnerB10AndReload } from './data-source';
const labels: Record<B10Decision, string> = { APPROVE: 'Approve category + authorize funding', HOLD: 'Hold', REJECT: 'Reject' };
export default function B10DecisionPanel({ product, ownerToken, reloadReal, notify }: { readonly product: Product; readonly ownerToken: string | null; readonly reloadReal: () => Promise<void>; readonly notify: (message: string) => void }) {
  const [selected, setSelected] = useState<B10Decision | null>(null); const [pending, setPending] = useState(false); const [message, setMessage] = useState('');
  const lock = product.b9.state === 'LOCKED' ? product.b9.locked : null; const effective = product.b10.effective;
  const submit = async () => { if (!selected || !ownerToken || !lock || pending || effective?.decision === selected) return; setPending(true); setMessage(''); try { const outcome = await submitOwnerB10AndReload({ productWorkspaceId: product.id, lockedStpId: lock.id, previousDecisionId: effective?.id ?? null, decision: selected, token: ownerToken }, reloadReal); setSelected(null); if (outcome === 'conflict') setMessage('Quyết định B10 hiệu lực đã thay đổi. Trạng thái mới nhất đã được tải lại; quyết định mới hơn không bị ghi đè.'); else notify('Đã ghi quyết định B10 và tải lại dữ liệu có thẩm quyền.'); } catch (error) { setMessage(error instanceof OwnerWriteError ? error.message : 'Không thể ghi quyết định B10.'); } finally { setPending(false); } };
  return <section className="b10-panel"><div className="heading compact"><div><h2>B10 · Danh mục và ủy quyền cấp vốn</h2><p>{product.name}</p></div><strong>{effective ? `#${effective.number} · ${effective.decision}` : 'Chưa có quyết định'}</strong></div><div className="source-row"><span>Locked STP<b>{lock ? `LOCKED_STP · ${lock.lockedAt}` : 'Chưa có locked STP đã xác minh'}</b></span><span>readyForB11<b>{product.b10.readyForB11 ? 'true' : 'false'}</b></span></div><div className="evidence"><h3>Ủy quyền không phải chuyển tiền</h3><p>APPROVE phê duyệt danh mục và cho phép sản phẩm nhận cấp vốn. Nó không phân bổ, chuyển hoặc chi bất kỳ khoản tiền nào và không tạo B11.</p></div><div className="decision-actions">{(['APPROVE','HOLD','REJECT'] as const).map((decision) => <button className={decision === 'APPROVE' ? 'pass' : decision.toLowerCase()} key={decision} disabled={ownerB10Disabled({ unlocked: ownerToken !== null, pending, lockedStpId: lock?.id ?? null, effective: effective?.decision ?? null, decision })} onClick={() => setSelected(decision)}>{pending ? 'Đang gửi…' : labels[decision]}</button>)}</div><p className="decision-note">Không yêu cầu thêm nội dung hay người đánh giá. Không có quyết định tự động.</p>{message && <p className="snapshot-warning" role="alert">{message}</p>}<h3>Lịch sử correction bất biến</h3>{product.b10.history.length ? <ol className="timeline">{product.b10.history.map((event) => <li key={event.id}><strong>#{event.number} · {event.decision}</strong><small>{event.decidedAt}{event.previousId ? ` · correction nối tiếp ${event.previousId}` : ' · quyết định đầu tiên'}</small></li>)}</ol> : <p>Chưa có lịch sử B10.</p>}{selected && <div className="confirm-backdrop" role="presentation"><div className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="b10-confirm-title"><h3 id="b10-confirm-title">Xác nhận {labels[selected]}?</h3><p>Đây là {effective ? `correction của quyết định #${effective.number}; correction sẽ nối thêm một quyết định bất biến vào lịch sử` : 'quyết định B10 đầu tiên với predecessor null'}.</p><p>APPROVE chỉ ủy quyền nhận cấp vốn; hành động này không phân bổ, chuyển hoặc chi tiền.</p><div className="confirm-actions"><button disabled={pending} onClick={() => setSelected(null)}>Hủy</button><button className="button primary" disabled={pending} onClick={() => void submit()}>Xác nhận quyết định</button></div></div></div>}</section>;
}
