import { useCallback, useState } from 'react';
import type { B10Decision, Product } from './model';
import { ownerB10Blocker, OwnerWriteError, submitOwnerB10AndReload } from './data-source';
import ConfirmDialog from './ConfirmDialog';
const labels: Record<B10Decision, string> = { APPROVE: 'Duyệt danh mục và cho phép nhận cấp vốn', HOLD: 'Tạm giữ', REJECT: 'Từ chối' };
const shortLabels: Record<B10Decision, string> = { APPROVE: 'Duyệt', HOLD: 'Tạm giữ', REJECT: 'Từ chối' };
export default function B10DecisionPanel({ product, ownerToken, writesAvailable = true, reloadReal, notify, navigateB9 }: { readonly product: Product; readonly ownerToken: string | null; readonly writesAvailable?: boolean; readonly reloadReal: () => Promise<void>; readonly notify: (message: string) => void; readonly navigateB9: () => void }) {
  const [selected, setSelected] = useState<B10Decision | null>(null); const [pending, setPending] = useState(false); const [message, setMessage] = useState('');
  const lock = product.b9.state === 'LOCKED' ? product.b9.locked : null; const effective = product.b10.effective;
  const blockerFor = (decision: B10Decision) => ownerB10Blocker({ writesAvailable, unlocked: ownerToken !== null, pending, lockedStpId: lock?.id ?? null, effective: effective?.decision ?? null, decision });
  const submit = async () => { if (!selected || blockerFor(selected)) return; setPending(true); setMessage(''); try { const outcome = await submitOwnerB10AndReload({ productWorkspaceId: product.id, lockedStpId: lock!.id, previousDecisionId: effective?.id ?? null, decision: selected, token: ownerToken! }, reloadReal); setSelected(null); if (outcome === 'conflict') setMessage('Trạng thái đã thay đổi ở nơi khác. Quyết định mới nhất đã được tải lại; hãy xem lại trước khi gửi.'); else notify('Đã ghi quyết định B10 và tải lại dữ liệu đã xác minh.'); } catch (error) { setMessage(error instanceof OwnerWriteError ? error.message : 'Không thể ghi quyết định B10.'); } finally { setPending(false); } };
  const close = useCallback(() => setSelected(null), []);
  let guidance: string;
  if (!writesAvailable) guidance = 'Chức năng ghi OWNER không khả dụng trong runtime này.';
  else if (pending) guidance = 'Yêu cầu đang được xử lý. Vui lòng chờ dữ liệu được tải lại.';
  else if (!lock) guidance = 'Chưa thể quyết định B10 vì STP chưa khóa.';
  else if (!ownerToken) guidance = 'OWNER đang khóa. Mở khóa OWNER để ghi hoặc sửa quyết định B10.';
  else guidance = effective ? 'Chọn một kết quả khác quyết định hiệu lực để thêm bản sửa bất biến.' : 'STP đã khóa. Có thể ghi quyết định B10 đầu tiên.';
  return <section className="b10-panel"><div className="heading compact"><div><h2>B10 · Phê duyệt danh mục và cấp vốn</h2><p>{product.name}</p></div><strong>{effective ? `Quyết định ${effective.number} · ${shortLabels[effective.decision]}` : 'Chưa có quyết định'}</strong></div><div className="source-row"><span>Điều kiện STP<b>{lock ? `STP chính thức đã khóa · ${lock.lockedAt}` : 'STP chưa khóa'}</b></span><span>Trạng thái tiếp theo<b>{product.b10.readyForB11 ? 'Đủ điều kiện B11' : 'Chưa đủ điều kiện B11'}</b></span></div>{product.b10.readyForB11 ? <div className="action-guidance success"><strong>Đã duyệt · Đủ điều kiện B11.</strong><p>B11 chưa được triển khai. Quyết định này không phân bổ, chuyển hoặc chi tiền.</p></div> : <div className="action-guidance"><strong>{guidance}</strong>{!lock && <button className="button quiet" onClick={navigateB9}>Về B9</button>}</div>}<div className="evidence"><h3>Phạm vi quyết định</h3><p>Duyệt nghĩa là phê duyệt danh mục và cho phép sản phẩm nhận cấp vốn. Đây không phải phân bổ, chuyển hoặc chi bất kỳ khoản tiền nào và không tự khởi tạo B11.</p></div><div className="decision-actions" aria-describedby="b10-action-guidance">{(['APPROVE','HOLD','REJECT'] as const).map((decision) => <button className={decision === 'APPROVE' ? 'pass' : decision.toLowerCase()} key={decision} disabled={blockerFor(decision) !== null} onClick={() => setSelected(decision)}>{pending ? 'Đang gửi…' : labels[decision]}</button>)}</div><p id="b10-action-guidance" className="decision-note">{guidance} Không yêu cầu lý do, ghi chú hay người đánh giá.</p>{message && <p className="snapshot-warning" role="alert">{message}</p>}<h3>Lịch sử quyết định bất biến</h3>{product.b10.history.length ? <ol className="timeline">{product.b10.history.map((event) => <li key={event.id}><strong>Quyết định {event.number} · {shortLabels[event.decision]}</strong><small>{event.decidedAt}{event.previousId ? ' · bản sửa nối tiếp quyết định trước' : ' · quyết định đầu tiên'}</small></li>)}</ol> : <p>Chưa có lịch sử B10.</p>}{selected && <ConfirmDialog titleId="b10-confirm-title" descriptionId="b10-confirm-description" title={`Xác nhận “${labels[selected]}”?`} confirmLabel="Xác nhận quyết định" pending={pending} onCancel={close} onConfirm={() => void submit()}><p id="b10-confirm-description">{effective ? `Đây là bản sửa nối tiếp quyết định ${effective.number}; quyết định cũ vẫn được giữ trong lịch sử.` : 'Đây là quyết định B10 đầu tiên.'}</p><p>Duyệt chỉ cho phép nhận cấp vốn; hành động này không phân bổ, chuyển hoặc chi tiền.</p></ConfirmDialog>}</section>;
}
