import { useRef, useState } from 'react';
import type { FormEvent } from 'react';
import type { Candidate, DemoState } from './model';
import { generatedCandidateKey, ownerCandidateDisabled, OwnerWriteError, submitOwnerCandidateAndReload } from './data-source';

export default function CandidateEditor({ mode, marketId, candidate, ownerToken, reloadReal, onSaved, onCancel, onDemoSave }: { readonly mode:'real'|'demo'; readonly marketId:string; readonly candidate?:Candidate; readonly ownerToken:string|null; readonly reloadReal:()=>Promise<DemoState>; readonly onSaved:(candidateId:string)=>void; readonly onCancel:()=>void; readonly onDemoSave:(input:{id:string;key:string;name:string;summary:string;revision:boolean})=>void }) {
  const [candidateKey] = useState(()=>candidate?.key ?? generatedCandidateKey());
  const [label,setLabel]=useState(candidate?.name??''); const [summary,setSummary]=useState(candidate?.summary??''); const [pending,setPending]=useState(false); const [message,setMessage]=useState(''); const inFlight=useRef(false);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(inFlight.current)return;const cleanLabel=label.trim(),cleanSummary=summary.trim();if(!cleanLabel||cleanLabel.length>200||cleanSummary.length>1000){setMessage('Kiểm tra lại tên ứng viên và phần tóm tắt.');return;}if(mode==='demo'){onDemoSave({id:candidate?.id??`candidate-demo-${Date.now().toString(36)}`,key:candidateKey,name:cleanLabel,summary:cleanSummary,revision:!!candidate});return;}if(!ownerToken)return;inFlight.current=true;setPending(true);setMessage('');try{const common={workspaceId:marketId,label:cleanLabel,...(cleanSummary?{summary:cleanSummary}:{}),token:ownerToken};const input=candidate?{...common,candidateId:candidate.id,expectedVersion:candidate.version}:{...common,candidateKey};const outcome=await submitOwnerCandidateAndReload(input,reloadReal);if(outcome.kind==='conflict')setMessage('Dữ liệu ứng viên đã thay đổi. Phiên bản mới nhất đã được tải lại; hãy đóng và mở lại biểu mẫu trước khi gửi.');else onSaved(outcome.receipt.candidateId);}catch(error){setMessage(error instanceof OwnerWriteError?error.message:'Không thể lưu ứng viên.');}finally{inFlight.current=false;setPending(false);}};
  return <section className="candidate-editor" aria-labelledby="candidate-editor-title"><div className="heading compact"><div><h3 id="candidate-editor-title">{candidate?'Chỉnh sửa ứng viên':'Thêm ứng viên sản phẩm'}</h3><p>{candidate?`Tạo phiên bản v${candidate.version+1}; phiên bản cũ và hồ sơ sản phẩm liên kết với nó vẫn được giữ nguyên.`:'Ứng viên mới chỉ ở trạng thái khám phá. Thao tác này chưa chọn sản phẩm, chưa tạo B7 và chưa tạo workspace sản phẩm.'}</p></div></div><form onSubmit={event=>void submit(event)}><label>Tên ứng viên hoặc ý tưởng sản phẩm — bắt buộc<input value={label} onChange={event=>setLabel(event.target.value)} maxLength={200} required autoFocus placeholder="Ví dụ: Canxi cho người trưởng thành" /></label><label>Tóm tắt — không bắt buộc<textarea value={summary} onChange={event=>setSummary(event.target.value)} maxLength={1000} placeholder="Phạm vi hoặc giả thuyết cần tiếp tục xác minh" /></label>{message&&<p className="form-error" role="alert">{message}</p>}<div className="form-actions"><button className="button primary" type="submit" disabled={mode==='real'?ownerCandidateDisabled({unlocked:ownerToken!==null,pending,label,summary}):pending}>{pending?'Đang lưu…':candidate?'Lưu phiên bản mới':'Tạo ứng viên'}</button><button className="button" type="button" disabled={pending} onClick={onCancel}>Hủy</button></div></form>{mode==='real'&&!ownerToken&&<p className="decision-note">Mở khóa OWNER cục bộ ở thanh phía trên để bật lưu.</p>}<p className="caption">Định danh kỹ thuật được tạo tự động và không hiển thị trong biểu mẫu.</p></section>;
}
